---
- name: Playbook to apply fixes to CIS Vulnarabilities
  hosts: "{{hostname}}"
  handlers:
  - name: active kernel parameter ip_forward
    ansible.builtin.shell: "{{item}}"
    listen: "active kernel parameter ip_forward"
    become: yes
    with_items:
    - sysctl -w net.ipv4.ip_forward=0 
    - sysctl -w net.ipv4.route.flush=1
  tasks:
  # 3.1.1 Ensure IP forwarding is disabled
  - name: 3.1.1 Ensure IP forwarding is disabled
    ansible.builtin.lineinfile:
      path: /etc/sysctl.conf
      line: "{{item}}"
    become: yes
    with_items:
    - "net.ipv4.ip_forward = 0"
    - "net.ipv6.conf.all.forwarding = 0"
    notify:
    - active kernel parameter ip_forward